name: Deploy to WordPress.org

on:
  push:
    tags:
    - "*"

jobs:
  tag:
    name: New tag
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v3
        with:
          node-version: '14'
      - uses: actions/checkout@main
      - name: Build
        run: |
          yarn install:all
          yarn build
      - name: WordPress Plugin Deploy
        uses: 10up/action-wordpress-plugin-deploy@stable
        env:
          SVN_PASSWORD: ${{ secrets.SVN_PASSWORD }}
          SVN_USERNAME: ${{ secrets.SVN_USERNAME }}
          SLUG: tradecast
          BUILD_DIR: src/wp-plugin/src
